services:
  sample-service-1:
    url: git@github.com:Parsa2820/test-git-compose.git
    branches:
      - name: master
        args:
          - name: arg1
            value: value1
      - name: feature/6
        from: master
        args:
          - name: arg1
            value: value1
          - name: arg2
            value: value2
  sample-service-2:
    url: git@github.com:Parsa2820/test-git-compose.git
    branches:
      - name: feature/7
        from: master
        args:
          - name: arg1
            value: value1
          - name: arg2
            value: value2